name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3
  - jupyterlab=1.0.9
  - matplotlib=3.1.1
  - nodejs=12.8
  - numpy=1.17.0
  - pandas=0.25.1
  - pandas-profiling=2.3.0
  - pip
  - python=3.7
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - pip:
    - datachile


