name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.3.0
  - jupyterlab=1.0.9
  - matplotlib=3.1.1
  - nodejs=12.8
  - numpy=1.17.0
  - pandas=0.25.1
  - pandas-profiling=2.3.0
  - pip
  - python=3.7
  - scikit-learn=0.22
  - scipy=1.3.1
  - seaborn=0.9.0
  - vega_datasets=0.7.0
  - Pillow=6.2.0
  - pip:
    - datachile
    - xmlx
  - lxml=4.5.0
  - ipywidgets=7.5.1

